version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: backend/core/Dockerfile
    volumes:
      - ./backend/core:/app
    ports:
      - "8000:8000"

  fastapi:
    build:
      context: .
      dockerfile: backend/api/Dockerfile
    volumes:
      - ./backend/api:/app
      - ./backend/api/data:/app/data
      - ./backend/api/models:/app/models
    ports:
      - "8001:8001"
    depends_on:
      - django
