version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: core/Dockerfile
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app
      - ./api/data:/app/data
      - ./api/models:/app/models
    ports:
      - "8001:8001"
